language: csharp  
sudo: false  
dist: trusty  
mono: none
dotnet: 2.1.300
script:
  - dotnet build MicroBolt.Stock.Web/MicroBolt.Stock.Web.csproj -c Release
  - dotnet build MicroBolt.Client.Web/MicroBolt.Client.Web.csproj -c Release
