language: csharp  
sudo: false  
dist: trusty  
mono: none
dotnet: 2.1.300
script:
  - dotnet restore MicroBolt.Stock.Web/MicroBolt.Stock.Web.csproj
  - dotnet build MicroBolt.Stock.Web/MicroBolt.Stock.Web.csproj  -c Release
