language: csharp  
sudo: false  
dist: trusty  
mono: none
dotnet: 2.1.300
install:
  - dotnet restore Microsoft.Extensions.Configuration.Abstractions --version 2.1.1
script:
  - dotnet build MicroBolt.Stock.Web/MicroBolt.Stock.Web.csproj -c Release
