language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.1.300
script:  
  - dotnet build MicroBolt.Stock.Web/MicroBolt.Stock.Web.csproj -c Release
before_install:
  - dotnet add package Microsoft.Extensions.Configuration.Abstractions --version 2.1.1
