version: '3.4'

services:
  microbolt.clients.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  microbolt.identity.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44335
    ports:
      - "59427:80"
      - "44335:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  microbolt.stock.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  microbolt.client.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

